apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-svc-deployment
  labels:
    app: product-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-svc
  template:
    metadata:
      labels:
        app: product-svc
    spec:
      containers:
      - name: product-svc
        image: rvpashok/nagp-product-service:latest
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
             name: svc-config
          - secretRef:
              name: product-svc-secret
      imagePullSecrets:
      - name: dockerhub-privaterepo-access