apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-deployment
spec:
  serviceName: "db-headless-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db-svc
  template:
    metadata:
      labels:
        app: mongo-db-svc
    spec:
      containers:
      - name: mongo-db-svc
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        volumeMounts:
        - name: data-volume
          mountPath: /data/db
      #volumes:
      #- name: data-volume
      #  persistentVolumeClaim:
      #    claimName: pv-claim
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi