apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-deployment
spec:
  serviceName: "db-headless-service"
  replicas: 1
  selector:
    matchLabels:
      app: product-db-svc
  template:
    metadata:
      labels:
        app: product-db-svc
    spec:
      containers:
      - name: product-db-svc
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME:
            valueFrom: 
              - secretRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD:
            valueFrom: 
              - secretRef:
                name: mongodb-secret
                key: mongo-root-password
          name: db-deployment
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi