apiVersion: v1
kind: Service
metadata:
  name: db-headless-service
  labels:
    app: product-db-svc
spec:
  ports:
  - port: 27017
    name: db-deployment
  clusterIP: None
  selector:
    app: product-db-svc