apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-express-deployment
spec:
  serviceName: "db-express-headless-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express-svc
  template:
    metadata:
      labels:
        app: mongo-express-svc
    spec:
      containers:
      - name: mongo-express-svc
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-database-url
        volumeMounts:
        - name: www1
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi